name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Linux x64 + clang

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        CXX=clang++ CC=clang cmake ..
    - name: make
      run: cd build && make
    - name: make check
      run: cd build && make check

